"$schema" = 'https://starship.rs/config-schema.json'

format = """
[](orange)\
$os\
$username\
[](bg:bg_yellow fg:orange)\
$directory\
[](fg:bg_yellow bg:green)\
$git_branch\
[](fg:green bg:blue)\
$docker_context\
[](fg:blue bg:bg_red)\
$time\
[ ](fg:bg_red)\
$line_break$character"""

palette = 'everforest'

[palettes.everforest]
fg0 = '#D3C6AA'
fg_green = '#63665B'
bg1 = '#343F44'
bg3 = '#232a2e'
bg4 = '#b9c0ab'
bg_green = '#93B259'
bg_red = '#92667D'
bg_yellow = '#DBBC7F'
gray = '#A6B0A0'
green = '#A7C080'
green_dark = '#48562C'
black = '#333732'
blue = '#7FBBB3'
blue_dark = '#224F67'
aqua = '#83C092'
orange = '#E69875'
purple = '#D699B6'
purple_dark = '#775666'
bgpurple = '#5c3f4f'
red = '#E67E80'
yellow = '#DBBC7F'
yellow_dark = '#7C6B4A'
teal = '#83C092'
surface0 = '#333c43' 
text = '#7fbbb3'

[os]
disabled = false
style = "bg:orange fg:blue_dark"

[os.symbols]
Linux = "󰌽"
Fedora = "󰣛"
Debian = "󰣚"
Redhat = "󱄛"

[username]
show_always = true
style_user = "bg:orange fg:blue_dark"
style_root = "bg:bg3 fg:text"
format = '[ $user ]($style)'

[directory]
style = "fg:yellow_dark bg:bg_yellow"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = "󰝚 "
"Pictures" = " "
"Developer" = "󰲋 "
"Desktop" = "󰨇 "

[git_branch]
style = "bg:green fg:fg_green"
symbol = "  "
format = "[$symbol$branch(:$remote_branch)]($style)"

[git_status]
style = "bg:green"
format = '[[($all_status$ahead_behind )](fg:base bg:green)]($style)'

[docker_context]
symbol = ""
style = "bg:blue"
format = '[[ $symbol( $context) ](fg:blue_dark bg:blue)]($style)'

[time]
disabled = false
time_format = "%R"
style = "bg:bg_red"
format = '[[  $time ](fg:black bg:bg_red)]($style)'

[line_break]
disabled = false

[character]
disabled = false
success_symbol = '[](bold fg:green)'
error_symbol = '[](bold fg:red)'
vimcmd_symbol = '[](bold fg:green)'
vimcmd_replace_one_symbol = '[](bold fg:purple)'
vimcmd_replace_symbol = '[](bold fg:purple)'
vimcmd_visual_symbol = '[](bold fg:lavender)'
