[colors]
draw_bold_text_with_bright_colors = true

[colors.bright]
black = "#475258"
blue = "#83C092"
cyan = "#83c092"
green = "#a7c080"
magenta = "#d699b6"
red = "#e67e80"
white = "#d3c6aa"
yellow = "#dbbc7f"

[colors.normal]
black = "#414b50"
blue = "#83C092"
cyan = "#83c092"
green = "#a7c080"
magenta = "#d699b6"
red = "#e67e80"
white = "#d3c6aa"
yellow = "#dbbc7f"

[colors.primary]
background = "#2D353B"
foreground = "#D3C6AA"

[cursor]
style = { shape = "Underline", blinking = "On" }

[font]
size = 12

[font.bold]
family = "JetBrainsMono"
style = "Bold"

[font.bold_italic]
family = "JetBrainsMono"
style = "BoldItalic"

[font.italic]
family = "JetBrainsMono"
style = "MediumItalic"

[font.normal]
family = "JetBrainsMono"
style = "Medium"

[window]

[window.class]
general = "Alacritty"
instance = "Alacritty"

[window.padding]
x = 5
y = 4

[scrolling]
history = 1000
multiplier = 3
