#!/bin/sh
# depends on weather icons: https://github.com/erikflowers/weather-icons

# your city id. To get it: got to https://openweathermap.org/, search for your city, the last 7 digits in the link will be your city id.
declare -i id=5337561

# api key from https://openweathermap.org/, you get it for free when you sign up.
api_key="c2a1840125d3bf08d86133c6ddbe0b3c"
icon_id=$(curl -sf "https://api.openweathermap.org/data/2.5/weather?id=$id&appid=$api_key&units=metric" | jq -r ."weather[0].icon")
temp=$(curl -sf "https://api.openweathermap.org/data/2.5/weather?id=$id&appid=$api_key&units=metric" | jq ."main.temp" | awk '{print int($1+0.5)}')

case $icon_id in
	01d) icon="";;
	01n) icon="";;
	02d) icon="";;
	02n) icon="";;
	03d) icon="";;
	03n) icon="";;
	04d) icon="";;
	04n) icon="";;
	09d) icon="";;
	09n) icon="";;
	10d) icon="";;
	10n) icon="";;
	11d) icon="";;
	11n) icon="";;
	13d) icon="";;
	13n) icon="";;
	50d) icon="";;
	50n) icon="";;
	*) icon="$icon_id";;
esac

get_weather()
{
	echo " $temp $icon "
}
get_weather

# %{F#d3c6aa} %{F-} - specifies what color to use for the icon
# %{Tx} <> %{T-} - specifies what font to use, replace x with the number of the font in the polybar config file
